/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayBookingIdRouteImport } from './routes/pay.$bookingId'
import { Route as BusinessesBusinessIdRouteImport } from './routes/businesses.$businessId'
import { Route as BookServiceIdRouteImport } from './routes/book.$serviceId'
import { Route as AuthProviderRouteImport } from './routes/auth.provider'
import { Route as AuthCustomerRouteImport } from './routes/auth.customer'
import { Route as AdminsAdminIdRouteImport } from './routes/admins.$adminId'
import { Route as AuthProviderBusinessRouteImport } from './routes/auth.provider.business'
import { Route as AuthCustomerProfileRouteImport } from './routes/auth.customer.profile'
import { Route as AdminsAdminIdBookingsBookingIdRouteImport } from './routes/admins.$adminId.bookings.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayBookingIdRoute = PayBookingIdRouteImport.update({
  id: '/pay/$bookingId',
  path: '/pay/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesBusinessIdRoute = BusinessesBusinessIdRouteImport.update({
  id: '/businesses/$businessId',
  path: '/businesses/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookServiceIdRoute = BookServiceIdRouteImport.update({
  id: '/book/$serviceId',
  path: '/book/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderRoute = AuthProviderRouteImport.update({
  id: '/auth/provider',
  path: '/auth/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCustomerRoute = AuthCustomerRouteImport.update({
  id: '/auth/customer',
  path: '/auth/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsAdminIdRoute = AdminsAdminIdRouteImport.update({
  id: '/admins/$adminId',
  path: '/admins/$adminId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProviderBusinessRoute = AuthProviderBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthProviderRoute,
} as any)
const AuthCustomerProfileRoute = AuthCustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthCustomerRoute,
} as any)
const AdminsAdminIdBookingsBookingIdRoute =
  AdminsAdminIdBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AdminsAdminIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admins/$adminId': typeof AdminsAdminIdRouteWithChildren
  '/auth/customer': typeof AuthCustomerRouteWithChildren
  '/auth/provider': typeof AuthProviderRouteWithChildren
  '/book/$serviceId': typeof BookServiceIdRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/auth/customer/profile': typeof AuthCustomerProfileRoute
  '/auth/provider/business': typeof AuthProviderBusinessRoute
  '/admins/$adminId/bookings/$bookingId': typeof AdminsAdminIdBookingsBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admins/$adminId': typeof AdminsAdminIdRouteWithChildren
  '/auth/customer': typeof AuthCustomerRouteWithChildren
  '/auth/provider': typeof AuthProviderRouteWithChildren
  '/book/$serviceId': typeof BookServiceIdRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/auth/customer/profile': typeof AuthCustomerProfileRoute
  '/auth/provider/business': typeof AuthProviderBusinessRoute
  '/admins/$adminId/bookings/$bookingId': typeof AdminsAdminIdBookingsBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admins/$adminId': typeof AdminsAdminIdRouteWithChildren
  '/auth/customer': typeof AuthCustomerRouteWithChildren
  '/auth/provider': typeof AuthProviderRouteWithChildren
  '/book/$serviceId': typeof BookServiceIdRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/pay/$bookingId': typeof PayBookingIdRoute
  '/auth/customer/profile': typeof AuthCustomerProfileRoute
  '/auth/provider/business': typeof AuthProviderBusinessRoute
  '/admins/$adminId/bookings/$bookingId': typeof AdminsAdminIdBookingsBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admins/$adminId'
    | '/auth/customer'
    | '/auth/provider'
    | '/book/$serviceId'
    | '/businesses/$businessId'
    | '/pay/$bookingId'
    | '/auth/customer/profile'
    | '/auth/provider/business'
    | '/admins/$adminId/bookings/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admins/$adminId'
    | '/auth/customer'
    | '/auth/provider'
    | '/book/$serviceId'
    | '/businesses/$businessId'
    | '/pay/$bookingId'
    | '/auth/customer/profile'
    | '/auth/provider/business'
    | '/admins/$adminId/bookings/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/admins/$adminId'
    | '/auth/customer'
    | '/auth/provider'
    | '/book/$serviceId'
    | '/businesses/$businessId'
    | '/pay/$bookingId'
    | '/auth/customer/profile'
    | '/auth/provider/business'
    | '/admins/$adminId/bookings/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminsAdminIdRoute: typeof AdminsAdminIdRouteWithChildren
  AuthCustomerRoute: typeof AuthCustomerRouteWithChildren
  AuthProviderRoute: typeof AuthProviderRouteWithChildren
  BookServiceIdRoute: typeof BookServiceIdRoute
  BusinessesBusinessIdRoute: typeof BusinessesBusinessIdRoute
  PayBookingIdRoute: typeof PayBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$bookingId': {
      id: '/pay/$bookingId'
      path: '/pay/$bookingId'
      fullPath: '/pay/$bookingId'
      preLoaderRoute: typeof PayBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$businessId': {
      id: '/businesses/$businessId'
      path: '/businesses/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof BusinessesBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$serviceId': {
      id: '/book/$serviceId'
      path: '/book/$serviceId'
      fullPath: '/book/$serviceId'
      preLoaderRoute: typeof BookServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/provider': {
      id: '/auth/provider'
      path: '/auth/provider'
      fullPath: '/auth/provider'
      preLoaderRoute: typeof AuthProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/customer': {
      id: '/auth/customer'
      path: '/auth/customer'
      fullPath: '/auth/customer'
      preLoaderRoute: typeof AuthCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/$adminId': {
      id: '/admins/$adminId'
      path: '/admins/$adminId'
      fullPath: '/admins/$adminId'
      preLoaderRoute: typeof AdminsAdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/provider/business': {
      id: '/auth/provider/business'
      path: '/business'
      fullPath: '/auth/provider/business'
      preLoaderRoute: typeof AuthProviderBusinessRouteImport
      parentRoute: typeof AuthProviderRoute
    }
    '/auth/customer/profile': {
      id: '/auth/customer/profile'
      path: '/profile'
      fullPath: '/auth/customer/profile'
      preLoaderRoute: typeof AuthCustomerProfileRouteImport
      parentRoute: typeof AuthCustomerRoute
    }
    '/admins/$adminId/bookings/$bookingId': {
      id: '/admins/$adminId/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/admins/$adminId/bookings/$bookingId'
      preLoaderRoute: typeof AdminsAdminIdBookingsBookingIdRouteImport
      parentRoute: typeof AdminsAdminIdRoute
    }
  }
}

interface AdminsAdminIdRouteChildren {
  AdminsAdminIdBookingsBookingIdRoute: typeof AdminsAdminIdBookingsBookingIdRoute
}

const AdminsAdminIdRouteChildren: AdminsAdminIdRouteChildren = {
  AdminsAdminIdBookingsBookingIdRoute: AdminsAdminIdBookingsBookingIdRoute,
}

const AdminsAdminIdRouteWithChildren = AdminsAdminIdRoute._addFileChildren(
  AdminsAdminIdRouteChildren,
)

interface AuthCustomerRouteChildren {
  AuthCustomerProfileRoute: typeof AuthCustomerProfileRoute
}

const AuthCustomerRouteChildren: AuthCustomerRouteChildren = {
  AuthCustomerProfileRoute: AuthCustomerProfileRoute,
}

const AuthCustomerRouteWithChildren = AuthCustomerRoute._addFileChildren(
  AuthCustomerRouteChildren,
)

interface AuthProviderRouteChildren {
  AuthProviderBusinessRoute: typeof AuthProviderBusinessRoute
}

const AuthProviderRouteChildren: AuthProviderRouteChildren = {
  AuthProviderBusinessRoute: AuthProviderBusinessRoute,
}

const AuthProviderRouteWithChildren = AuthProviderRoute._addFileChildren(
  AuthProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminsAdminIdRoute: AdminsAdminIdRouteWithChildren,
  AuthCustomerRoute: AuthCustomerRouteWithChildren,
  AuthProviderRoute: AuthProviderRouteWithChildren,
  BookServiceIdRoute: BookServiceIdRoute,
  BusinessesBusinessIdRoute: BusinessesBusinessIdRoute,
  PayBookingIdRoute: PayBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
